### PR TITLE
Fix broken links and remove obsolete notes.

### PR DESCRIPTION
**Pull request by gkellogg**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/27.html" title="Last updated on Mar 30, 2023, 8:40 PM UTC (836a31f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/27/7d01308...836a31f.html" title="Last updated on Mar 30, 2023, 8:40 PM UTC (836a31f)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
Draft until other PRs are merged and this is re-checked.

**Comment by hartig** [comment]
Gregg, why are these editor notes / questions obsolete now?

**Review by domel — APPROVED** [review]

**Comment by gkellogg** [comment]
> Gregg, why are these editor notes / questions obsolete now?

The notes are related to duplicate term definitions, which is addressed in https://github.com/w3c/rdf-semantics/pull/17. This PR presumes that those changes are made, but is in draft because it also depends on other parallel changes.

If it's clear that **denote** is defined in RDF Concepts and not RDF Semantics and those changes are made, then the purpose of the note has been fulfilled. The "ednote" class is there specifically to remind editors of things to attend to.

**Comment by hartig** [comment]
Thanks for the clarification. I was not aware of https://github.com/w3c/rdf-semantics/pull/17

**Review by hartig — APPROVED** [review]

**Pull request merged**
